### ISSUE TITLE
Blank emoji on app names

### ISSUE THREAD

**Issue by LI0NOFGOD** [PoomSmart/EmojiFonts#1]
There’s a bug when you have apps installed with emoji on the homescreen it doesnt display, even when you’re on an unjailbroken state it does the same thing. To recreate the bug you’ll have to sign an app through a 3rd party with the emoji icon. I’ve also attached a picture of the bug

![](https://i.imgur.com/xksUJfJ.jpeg)

**Comment by PoomSmart** [comment]
I don't see the picture.

**Comment by LI0NOFGOD** [comment]
Here is the link to link with the image of the homescreen emoji bug https://imgur.com/a/esLIHWT

**Comment by PoomSmart** [comment]
Which font you are using?

**Comment by LI0NOFGOD** [comment]
15.4 font on ios 14.8 11pro max unc0ver

**Comment by PoomSmart** [comment]
Did you use EmojiFontManager to install the font? How did you get the font?

**Comment by LI0NOFGOD** [comment]
Yes. After installing emojifontmanager v1.1.7 and emoji ios 15.4 (EFM) v1.0.2, i then selected it from emoji FontManager to enable it, all of the new emojis load fine and most of the bugs were fixed with the updates, however the homescreen bug is the one that remains. I’ve restored rootfs to troubleshoot the issue to makes sure it not another tweak and it wasnt till i reinstalled the mention tweaks the issue returned

**Comment by PoomSmart** [comment]
But are you sure that the name with emoji of those apps are actually emoji? They could very well be just pictographic characters.

**Comment by LI0NOFGOD** [comment]
Yes. I selected the name and emoji myself to tell apart the certificate apps from the the actual ones that are from the appstore. For a while now it shows up on my home screen till i’ve installed the emojifontsmanager along with the resources and emoji ios 15.4. And That when the apps with the emoji started to turn like the picture i sent you and even when i sign the new apps with another kind of emoji it does the same thing the app works fine. And if you’re curious about the app that i use to sign apps it’s called ipastore. I also have it on another device and it sign the apps with the emoji perfectly running the same ios 14.8. To fix the bug from showing up i had to restore rootfs

**Comment by LI0NOFGOD** [comment]
It’s funny that you’ve mentioned the folder emoji 
I just found this out now https://imgur.com/a/4Ii2RAY

the 2nd device has no bugs
