### ISSUE TITLE
Wrong emojis displayed on iOS 10

### ISSUE THREAD

**Issue by OctoNezd** [PoomSmart/EmojiFonts#10]
iOS 10, doubleh3lix through totallynotspyware on iPhone 5S
What is displayed (Telegram):
![Unsaved Image 2](https://github.com/PoomSmart/EmojiFonts/assets/15308404/d9a2b490-95b7-4584-a40a-200961f71512)
What should be displayed:
![image](https://github.com/PoomSmart/EmojiFonts/assets/15308404/a20b54bc-8461-4a67-93b6-533b5d3b3bf6)
Same is happening in EFM settings in preferences app, I assume rocket emoji should be displayed per https://github.com/PoomSmart/EmojiFontManager/blob/75e91cc8cadda63d7533fdd62d7e4b97334c71f3/EFMPref.m#L79:
![IMG_0005](https://github.com/PoomSmart/EmojiFonts/assets/15308404/ce8cdf00-65ed-4294-a66c-d3c8356d61d6)
Installed emoji packages:
![IMG_0006](https://github.com/PoomSmart/EmojiFonts/assets/15308404/df2540d7-7bf2-4d63-8275-b1d1213df6ef)
![IMG_0007](https://github.com/PoomSmart/EmojiFonts/assets/15308404/093b117d-da70-4032-a40d-67e970a170fe)
If I select Default instead of AppleColorEmoji correct emojis are displayed but I dont have any new emojis, obviously.

**Comment by PoomSmart** [comment]
@OctoNezd Which iOS 10 version is this?

**Comment by OctoNezd** [comment]
10.3.3 on 5S downgraded using legacy-ios-kit

**Comment by PoomSmart** [comment]
Upgrade EmojiFontManager to 1.3.5
