### ISSUE TITLE
noto T-rex is a broccoli on macOS

### ISSUE THREAD

**Issue by Hen-Rex** [PoomSmart/EmojiFonts#13]
There was some sort of update to macOS Sonoma that turned my T-rex into a broccoli 😂. I thought that was so weird until I discovered that I actually had this font installed (noto), but just forgot about it. Solution is update to latest release (15.1), it transforms the angry broccoli into a cute t-rex again.

Could be cool to have it auto-update the font through Homebrew.

**Comment by Cathie-UG** [comment]
Hi Hen-Rex! 

Sorry for reaching out out of the blue! I'm facing a similar issue after updating to Sonoma 14.5. I tried the usual method of downloading the font and placing it in ~/Library/Fonts/Apple Color Emoji.ttc, but it doesn't seem to work anymore.

Could you please share how you managed to change the font on your macOS? I'm hoping to fix this and would appreciate any advice you can offer.

**Comment by PoomSmart** [comment]
Possibly fixed, you may redownload the font.
