### ISSUE TITLE
[Request] Unicode 15.1 update for Fluent Emoji 

### ISSUE THREAD

**Issue by dora727** [PoomSmart/EmojiFonts#18]
It is updated for Windows 11 23H2 build 22621.3810 if (i’m correct), so would be nice if its updated for efm too

**Comment by PoomSmart** [comment]
Added.

**Comment by dora727** [comment]
hi, sry for digging, however somehow i can’t get it working. i tried to update, reinstall the pack but the new emojis wont show

**Comment by PoomSmart** [comment]
Fixed it. Refresh your sources then reinstall the package.
