### ISSUE TITLE
Some Emojis don’t show up on Regular version

### ISSUE THREAD

**Issue by hero3210** [PoomSmart/EmojiFonts#2]
Thanks for your huge efforts in porting the latest Emoji fonts to jailbreak users.

![51EC1100-6CF0-40F6-9C19-5ECA654AC5A7](https://user-images.githubusercontent.com/37654808/162958960-9f9c26b4-6bc0-4779-bf41-e5f3481fe29e.jpeg)

Issue: palm tree emoji (& probably others) does not appear when using the Regular iOS 15.4 EmojiFontManager font.

![3192732C-7F89-4712-B771-7467843303E3](https://user-images.githubusercontent.com/37654808/162959137-92c36131-66e0-42e5-9e7c-4ca16312341f.jpeg)

When using the Native version, everything works fine.

here’s the problematic text (it’s also problematic here on github):


iPhone X -  unc0ver - iOS 14.3

**Comment by PoomSmart** [comment]
@hero3210 Which app that has this issue?

**Comment by hero3210** [comment]
@PoomSmart  WhatsApp

**Comment by PoomSmart** [comment]
@hero3210 and where in the app do those problematic emojis display? I tried to reproduce the issue on my iPadOS 14.3 but to no avail.

**Comment by hero3210** [comment]
Sorry for the late reply. 
It appeared in a group name but when I tried to reproduce it I wasn’t able to. 

But by copying the exact text from the group name the problem is still reproducible.

here’s the problematic text:


**Comment by hero3210** [comment]
This happens on Regular v1.1.0 as well

**Comment by moh-ter** [comment]
Just leaving this here if you ever decide to take a look at it…


It seems like SoftBank (also iOS 4?) emojis do not get “translated” to the unicode equivalent in some apps while the Regular version is installed. This issue does not occur in the Native version (which is not installable as a package in XinaA15).

E.g.

(xE307) does not appear, but its unicode equivalent 🌴
(x1F334) appears

(xE011) does not appear, but its unicode equivalent ✌️(x270C) appears.

(xE51F) does not appear, but its unicode equivalent 💃(x1F483) appears.


This might be useful:
https://github.com/google/emoji4unicode/blob/master/data/emoji4unicode.xml
It has many SoftBank emoji codes & their unicode equivalents.

Also, this page might be useful to see the hex code of the emojis:
https://r12a.github.io/app-conversion/

**Comment by PoomSmart** [comment]
Gracefully fixed.

**Comment by hero3210** [comment]
Thanks so much.
