### ISSUE TITLE
oneui missing emoji list: ['1f441_1f5e8']

### ISSUE THREAD

**Issue by dayanch96** [PoomSmart/EmojiFonts#4]
Everything goes well except this issue and even generated ttc file but wdbfontoverwrite cant repack it

**Comment by dayanch96** [comment]
and, btw, script cant find his .py files so i edited it like below:

python3 EmojiFonts/$NAME.py common/${APPLE_FONT_NAME}_00.ttf $NAME/$FONT_NAME.ttf $NAME/$FONT_NAME.G_S_U_B_.ttx
python3 EmojiFonts/$NAME.py common/${APPLE_FONT_NAME}_01.ttf $NAME/$FONT_NAME.ttf $NAME/$FONT_NAME.G_S_U_B_.ttx

python3 EmojiFonts/otf2otc.py $NAME/${APPLE_FONT_NAME}_00.ttf $NAME/${APPLE_FONT_NAME}_01.ttf -o $NAME/$NAME.ttc

**Comment by dayanch96** [comment]
weird, works perfect on macos

**Comment by dayanch96** [comment]
tried again and it works. here ttc file if needed: https://disk.yandex.com/d/QZ2JC15OHwzGoQ

**Comment by PoomSmart** [comment]
@dayanch96 What exactly did you do?

**Comment by PoomSmart** [comment]
And that one missing emoji is actually missing from One UI 5.0 itself. I could later on maybe use the emoji design from older version of One UI.

**Comment by dayanch96** [comment]
> @dayanch96 What exactly did you do?

added ‘EmojiFonts/‘ folder name before $NAME.py and otf2otc.py in the last 3 strings

**Comment by dayanch96** [comment]
> And that one missing emoji is actually missing from One UI 5.0 itself. I could later on maybe use the emoji design from older version of One UI.

i guess its these emojis: 
![E0205CAE-4A55-4BBC-A06A-521E23691A55](https://user-images.githubusercontent.com/38832025/210502540-a86cea88-8871-49bb-bbcc-2f5d6254127f.jpeg)

Most likely ttf author might ported it incorrectly. I’ll try to find previous versions

**Comment by dayanch96** [comment]
same thing with joypixels from your release :(

Used WDBFontOverwrite 1.9.1

![595DE174-C505-4A82-8B69-4BFB760CBE5F](https://user-images.githubusercontent.com/38832025/210506633-23b3624f-bf99-432e-a729-cfa26484b395.jpeg)
![30DCA854-F952-446A-A266-B450B8E9FC05](https://user-images.githubusercontent.com/38832025/210506643-de0b833c-f4d5-4be2-994c-a2226c41bdfe.jpeg)

**Comment by PoomSmart** [comment]
And the missing emoji I was talking about is: 👁️‍🗨️

**Comment by dayanch96** [comment]
> CAVEATS.md

Apologize for my carelessness
