### ISSUE TITLE
TS user 😂

### ISSUE THREAD

**Issue by baranazal** [PoomSmart/EmojiFonts#5]
IOS 14.5 
TrollStore user 
15.4 new emojis does not appear 

Note : tried the LQ version it is LQ now but without the new ones 
thoughts?

**Comment by PoomSmart** [comment]
https://twitter.com/poomsmart/status/1626543705527308288?s=46&t=6yG-a-1GLJ3QST7cmYmjtQ

My thought is that this issue is invalid.

**Comment by baranazal** [comment]
15.4 not 16.4

**Comment by PoomSmart** [comment]
Same idea. "You can't see new emojis without a jailbreak"
